### ISSUE TITLE
Please bring back GUIDs, I love GUIDs, useful for distributed systems & PK reuse

### ISSUE THREAD

**Issue by beautifulcoder** [quakkels/pointing-online#2]
- Why use sequential IDs versus GUIDs?
- Why use an INT as a clustering key?
- Why should I care about table size (they are just bytes!)?

I feel there are many unanswered questions regarding GUIDs in SQL.

**Comment by quakkels** [comment]
Might add a token field for users in the future. But I'm happy with using ints as primary keys at this stage of development.
